apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-service
  template:
    metadata:
      labels:
        app: products-service
    spec:
      containers:
        - name: products-service
          image: yashwanth1129/products-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"

            - name: MYSQL_HOST
              value: "192.168.1.107"

            - name: MYSQL_PORT
              value: "3306"

            - name: MYSQL_DATABASE
              value: "ecommerceproductsdatabase"

            - name: MYSQL_USER
              value: "root"

            - name: MYSQL_PASSWORD
              value: "yash@123"